import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const roboto = Roboto({ weight: ["100", "300", "400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Demo Blog Design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>

        <div className="max-w-7xl mx-auto">
          <Navbar />
        </div>

        <div className="max-w-7xl mx-auto px-2">
          {children}
        </div>

        <div className="w-full mx-auto mt-5">
          <Footer />
        </div>
      </body>
    </html>
  );
}
